import type {
  Operator,
  OperatorActivity,
  OperatorDocument,
  OperatorStats,
  PermissionCategory,
} from '../types';

export const OPERATOR_STATS: OperatorStats = {
  total: 84,
  active: 67,
  pending: 12,
  suspended: 5,
};

export const DEPARTMENTS = [
  'IT & Infrastructure',
  'Operations',
  'Finance',
  'Compliance',
  'Customer Support',
] as const;

const AVATARS = [
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=128&h=128&fit=crop&crop=face',
  'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=128&h=128&fit=crop&crop=face',
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=128&h=128&fit=crop&crop=face',
  'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=128&h=128&fit=crop&crop=face',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=128&h=128&fit=crop&crop=face',
  'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=128&h=128&fit=crop&crop=face',
  'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=128&h=128&fit=crop&crop=face',
  'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=128&h=128&fit=crop&crop=face',
  'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=128&h=128&fit=crop&crop=face',
];

export const OPERATORS: Operator[] = [
  {
    id: 'ops-884',
    employeeId: 'OPS-2024-884',
    name: 'Rajesh Kumar',
    role: 'Senior Field Operator',
    department: 'Operations',
    status: 'active',
    avatarUrl: AVATARS[0],
    joinedDate: '12/01/2024',
    lastActive: '2 mins ago',
    email: 'rajesh.kumar@cybersave.gov.in',
    phone: '+91 98765 43210',
    dateOfBirth: '15/03/1988',
    address: '14 Hazratganj, Lucknow, UP 226001',
    supervisorName: 'Rajesh Kumar',
    supervisorRole: 'Direct Supervisor (Super Admin)',
    shift: 'Day Shift (09:00 - 18:00)',
    twoFactorEnabled: true,
    lastLogin: '06 Aug 2026, 09:14 AM',
    activeSessions: 2,
    ipWhitelisting: true,
    metrics: {
      tasksCompleted: 342,
      tasksTrend: '+12% MoM',
      avgResponseTime: '2.4 hrs',
      responseBadge: 'Top 5%',
      satisfaction: 4.8,
      documentsProcessed: 1247,
      accuracy: '99.2% Accuracy',
    },
  },
  {
    id: 'ops-201',
    employeeId: 'OPS-2024-201',
    name: 'Arjun Mehta',
    role: 'System Admin',
    department: 'IT & Infrastructure',
    status: 'active',
    avatarUrl: AVATARS[2],
    joinedDate: '12/01/2024',
    lastActive: '2 mins ago',
    email: 'arjun.mehta@cybersave.gov.in',
    phone: '+91 98111 22334',
    dateOfBirth: '22/07/1990',
    address: 'Sector 18, Noida, UP',
    supervisorName: 'Rajesh Kumar',
    supervisorRole: 'Super Admin',
    shift: 'Day Shift (09:00 - 18:00)',
    twoFactorEnabled: true,
    lastLogin: '06 Aug 2026, 08:40 AM',
    activeSessions: 1,
    ipWhitelisting: true,
    metrics: {
      tasksCompleted: 210,
      tasksTrend: '+8% MoM',
      avgResponseTime: '3.1 hrs',
      responseBadge: 'Top 15%',
      satisfaction: 4.5,
      documentsProcessed: 890,
      accuracy: '98.1% Accuracy',
    },
  },
  {
    id: 'ops-202',
    employeeId: 'OPS-2024-202',
    name: 'Priya Sharma',
    role: 'Field Operator',
    department: 'Operations',
    status: 'active',
    avatarUrl: AVATARS[1],
    joinedDate: '03/15/2024',
    lastActive: '15 mins ago',
    email: 'priya.sharma@cybersave.gov.in',
    phone: '+91 98222 33445',
    dateOfBirth: '10/11/1992',
    address: 'Indiranagar, Bengaluru',
    supervisorName: 'Rajesh Kumar',
    supervisorRole: 'Super Admin',
    shift: 'Day Shift (09:00 - 18:00)',
    twoFactorEnabled: true,
    lastLogin: '06 Aug 2026, 10:02 AM',
    activeSessions: 1,
    ipWhitelisting: false,
    metrics: {
      tasksCompleted: 188,
      tasksTrend: '+5% MoM',
      avgResponseTime: '2.9 hrs',
      responseBadge: 'Top 20%',
      satisfaction: 4.6,
      documentsProcessed: 640,
      accuracy: '97.8% Accuracy',
    },
  },
  {
    id: 'ops-203',
    employeeId: 'OPS-2024-203',
    name: 'Vikram Singh',
    role: 'Compliance Officer',
    department: 'Compliance',
    status: 'pending',
    avatarUrl: AVATARS[4],
    joinedDate: '07/20/2024',
    lastActive: 'Never',
    email: 'vikram.singh@cybersave.gov.in',
    phone: '+91 98333 44556',
    dateOfBirth: '05/01/1987',
    address: 'Civil Lines, Jaipur',
    supervisorName: 'Rajesh Kumar',
    supervisorRole: 'Super Admin',
    shift: 'Day Shift (09:00 - 18:00)',
    twoFactorEnabled: false,
    lastLogin: '—',
    activeSessions: 0,
    ipWhitelisting: false,
    metrics: {
      tasksCompleted: 0,
      tasksTrend: '—',
      avgResponseTime: '—',
      responseBadge: 'New',
      satisfaction: 0,
      documentsProcessed: 0,
      accuracy: '—',
    },
  },
  {
    id: 'ops-204',
    employeeId: 'OPS-2024-204',
    name: 'Ananya Reddy',
    role: 'Support Lead',
    department: 'Customer Support',
    status: 'active',
    avatarUrl: AVATARS[3],
    joinedDate: '01/08/2024',
    lastActive: '1 hour ago',
    email: 'ananya.reddy@cybersave.gov.in',
    phone: '+91 98444 55667',
    dateOfBirth: '18/09/1991',
    address: 'Banjara Hills, Hyderabad',
    supervisorName: 'Rajesh Kumar',
    supervisorRole: 'Super Admin',
    shift: 'Day Shift (09:00 - 18:00)',
    twoFactorEnabled: true,
    lastLogin: '06 Aug 2026, 11:20 AM',
    activeSessions: 2,
    ipWhitelisting: true,
    metrics: {
      tasksCompleted: 276,
      tasksTrend: '+9% MoM',
      avgResponseTime: '1.8 hrs',
      responseBadge: 'Top 3%',
      satisfaction: 4.9,
      documentsProcessed: 1120,
      accuracy: '99.0% Accuracy',
    },
  },
  {
    id: 'ops-205',
    employeeId: 'OPS-2024-205',
    name: 'Mohammed Irfan',
    role: 'Finance Operator',
    department: 'Finance',
    status: 'suspended',
    avatarUrl: AVATARS[6],
    joinedDate: '11/02/2023',
    lastActive: '5 days ago',
    email: 'm.irfan@cybersave.gov.in',
    phone: '+91 98555 66778',
    dateOfBirth: '30/04/1985',
    address: 'Charminar, Hyderabad',
    supervisorName: 'Rajesh Kumar',
    supervisorRole: 'Super Admin',
    shift: 'Day Shift (09:00 - 18:00)',
    twoFactorEnabled: true,
    lastLogin: '01 Aug 2026, 04:12 PM',
    activeSessions: 0,
    ipWhitelisting: true,
    metrics: {
      tasksCompleted: 410,
      tasksTrend: '-2% MoM',
      avgResponseTime: '4.2 hrs',
      responseBadge: 'Review',
      satisfaction: 4.1,
      documentsProcessed: 1502,
      accuracy: '96.4% Accuracy',
    },
  },
  {
    id: 'ops-206',
    employeeId: 'OPS-2024-206',
    name: 'Sneha Patel',
    role: 'Field Operator',
    department: 'Operations',
    status: 'active',
    avatarUrl: AVATARS[5],
    joinedDate: '05/12/2024',
    lastActive: '30 mins ago',
    email: 'sneha.patel@cybersave.gov.in',
    phone: '+91 98666 77889',
    dateOfBirth: '12/12/1993',
    address: 'Navrangpura, Ahmedabad',
    supervisorName: 'Rajesh Kumar',
    supervisorRole: 'Super Admin',
    shift: 'Day Shift (09:00 - 18:00)',
    twoFactorEnabled: true,
    lastLogin: '06 Aug 2026, 09:55 AM',
    activeSessions: 1,
    ipWhitelisting: true,
    metrics: {
      tasksCompleted: 154,
      tasksTrend: '+11% MoM',
      avgResponseTime: '2.6 hrs',
      responseBadge: 'Top 10%',
      satisfaction: 4.7,
      documentsProcessed: 520,
      accuracy: '98.5% Accuracy',
    },
  },
  {
    id: 'ops-207',
    employeeId: 'OPS-2024-207',
    name: 'Karan Malhotra',
    role: 'IT Specialist',
    department: 'IT & Infrastructure',
    status: 'pending',
    avatarUrl: AVATARS[8],
    joinedDate: '08/01/2024',
    lastActive: 'Never',
    email: 'karan.m@cybersave.gov.in',
    phone: '+91 98777 88990',
    dateOfBirth: '08/06/1989',
    address: 'Andheri West, Mumbai',
    supervisorName: 'Rajesh Kumar',
    supervisorRole: 'Super Admin',
    shift: 'Night Shift (21:00 - 06:00)',
    twoFactorEnabled: false,
    lastLogin: '—',
    activeSessions: 0,
    ipWhitelisting: false,
    metrics: {
      tasksCompleted: 0,
      tasksTrend: '—',
      avgResponseTime: '—',
      responseBadge: 'New',
      satisfaction: 0,
      documentsProcessed: 0,
      accuracy: '—',
    },
  },
  {
    id: 'ops-208',
    employeeId: 'OPS-2024-208',
    name: 'Fatima Begum',
    role: 'Compliance Analyst',
    department: 'Compliance',
    status: 'active',
    avatarUrl: AVATARS[7],
    joinedDate: '02/28/2024',
    lastActive: '3 hours ago',
    email: 'fatima.b@cybersave.gov.in',
    phone: '+91 98888 99001',
    dateOfBirth: '25/02/1990',
    address: 'Park Street, Kolkata',
    supervisorName: 'Rajesh Kumar',
    supervisorRole: 'Super Admin',
    shift: 'Day Shift (09:00 - 18:00)',
    twoFactorEnabled: true,
    lastLogin: '06 Aug 2026, 07:30 AM',
    activeSessions: 1,
    ipWhitelisting: true,
    metrics: {
      tasksCompleted: 198,
      tasksTrend: '+6% MoM',
      avgResponseTime: '3.4 hrs',
      responseBadge: 'Top 18%',
      satisfaction: 4.4,
      documentsProcessed: 710,
      accuracy: '98.8% Accuracy',
    },
  },
];

export const OPERATOR_ACTIVITIES: OperatorActivity[] = [
  { id: 'a1', dateTime: '06 Aug 2026, 10:42', action: 'Document verification completed', status: 'success', ip: '103.21.244.12' },
  { id: 'a2', dateTime: '06 Aug 2026, 09:18', action: 'Login from new device', status: 'warning', ip: '49.36.112.8' },
  { id: 'a3', dateTime: '05 Aug 2026, 16:05', action: 'Application status updated', status: 'success', ip: '103.21.244.12' },
  { id: 'a4', dateTime: '05 Aug 2026, 14:22', action: 'Failed password attempt', status: 'error', ip: '122.168.44.9' },
  { id: 'a5', dateTime: '05 Aug 2026, 11:10', action: 'Citizen profile viewed', status: 'success', ip: '103.21.244.12' },
];

export const PERMISSION_CATEGORIES: PermissionCategory[] = [
  {
    id: 'fleet',
    title: 'Fleet Management',
    enabled: true,
    permissions: [
      { id: 'f1', title: 'Register & Manage Vehicles', description: 'Add and update vehicle registry records.', enabled: true },
      { id: 'f2', title: 'Dispatch Operations Control', description: 'Assign and reassign field dispatches.', enabled: true },
      { id: 'f3', title: 'Configure Telematics Rules', description: 'Edit telematics thresholds and alerts.', enabled: false },
    ],
  },
  {
    id: 'docs',
    title: 'Documents & Compliance',
    enabled: true,
    permissions: [
      { id: 'd1', title: 'Verify Driver Credentials', description: 'Approve or reject credential submissions.', enabled: true },
      { id: 'd2', title: 'Issue Legal Compliance Overrides', description: 'Apply temporary compliance exceptions.', enabled: false },
      { id: 'd3', title: 'Purge Expired Audit Files', description: 'Permanently delete expired audit archives.', enabled: false },
    ],
  },
  {
    id: 'alerts',
    title: 'Alerts & Notifications',
    enabled: true,
    permissions: [
      { id: 'n1', title: 'Broadcast Emergency Messages', description: 'Send emergency broadcasts to centres.', enabled: true },
      { id: 'n2', title: 'Configure Slack/Webhooks Alerts', description: 'Manage outbound webhook integrations.', enabled: true },
    ],
  },
  {
    id: 'reports',
    title: 'Reports & Analytics',
    enabled: true,
    permissions: [
      { id: 'r1', title: 'Generate Monthly Compliance Audits', description: 'Create scheduled compliance reports.', enabled: true },
      { id: 'r2', title: 'Export Raw Telemetry Streams', description: 'Download raw telemetry datasets.', enabled: true },
    ],
  },
  {
    id: 'users',
    title: 'User Management',
    enabled: false,
    permissions: [
      { id: 'u1', title: 'Create Field Operator Accounts', description: 'Provision new operator accounts.', enabled: false },
      { id: 'u2', title: 'Modify Operator Security Access', description: 'Change operator permission tiers.', enabled: false },
    ],
  },
];

export const OPERATOR_DOCUMENTS: OperatorDocument[] = [
  { id: 'doc1', title: 'Government ID', maskedId: '**** 4820', type: 'pdf', status: 'verified', uploaded: '12/01/2024', expires: 'N/A' },
  { id: 'doc2', title: 'Driving License', maskedId: '**** 7712', type: 'image', status: 'valid', uploaded: '12/01/2024', expires: '12/01/2028' },
  { id: 'doc3', title: 'PAN Card', maskedId: '**** 3391', type: 'pdf', status: 'verified', uploaded: '12/02/2024', expires: 'N/A' },
  { id: 'doc4', title: 'Passport', maskedId: '**** 5540', type: 'image', status: 'pending', uploaded: '01/15/2025', expires: '01/15/2030' },
  { id: 'doc5', title: 'Hazmat Certification', maskedId: '**** 1102', type: 'pdf', status: 'expired', uploaded: '06/01/2023', expires: '06/01/2025' },
  { id: 'doc6', title: 'Address Proof', maskedId: '**** 8821', type: 'pdf', status: 'verified', uploaded: '12/01/2024', expires: 'N/A' },
  { id: 'doc7', title: 'Police Verification', maskedId: '**** 4410', type: 'pdf', status: 'verified', uploaded: '12/10/2024', expires: '12/10/2027' },
  { id: 'doc8', title: 'Medical Fitness', maskedId: '**** 2298', type: 'image', status: 'valid', uploaded: '03/01/2025', expires: '03/01/2026' },
];

export const POLICY_CHANGES = [
  { id: 'p1', title: 'Enabled Webhook Alerts', by: 'System Admin', date: '24 Jan 2026' },
  { id: 'p2', title: 'Disabled Telemetry Export', by: 'System', date: '18 Jan 2026' },
  { id: 'p3', title: 'Granted Dispatch Control', by: 'System Admin', date: '10 Jan 2026' },
];
