import { FormFieldType } from '@prisma/client';

export type FormFieldSeed = {
  label: string;
  key: string;
  type: FormFieldType;
  required?: boolean;
  placeholder?: string;
};

export type StatePortalSeed = {
  code: string;
  name: string;
  portalUrl: string;
  platformFee?: number;
  baseFeeOverride?: number;
  processingTime?: string;
  department?: string;
};

export type SubServiceSeed = {
  slug: string;
  name: string;
  description: string;
  displayName: string;
  shortDescription: string;
  richDescription: string;
  instructions: string;
  processingTime: string;
  department: string;
  baseFee: number;
  serviceFee?: number;
  requiresState: boolean;
  defaultPortalUrl?: string;
  defaultPlatformFee?: number;
  manualInstructions?: string;
  statePortals?: StatePortalSeed[];
  formFields: FormFieldSeed[];
  documents: string[];
};

export type MainServiceSeed = {
  slug: string;
  name: string;
  description: string;
  sortOrder: number;
  subServices: SubServiceSeed[];
};

const COMMON_STATES: StatePortalSeed[] = [
  { code: 'MH', name: 'Maharashtra', portalUrl: 'https://aaplesarkar.mahaonline.gov.in/', platformFee: 49, baseFeeOverride: 15, processingTime: '7-15 days', department: 'Revenue Department' },
  { code: 'KA', name: 'Karnataka', portalUrl: 'https://sevasindhu.karnataka.gov.in/', platformFee: 49, baseFeeOverride: 20, processingTime: '10-20 days', department: 'Revenue Department' },
  { code: 'DL', name: 'Delhi', portalUrl: 'https://edistrict.delhigovt.nic.in/', platformFee: 49, baseFeeOverride: 15, processingTime: '7-12 days', department: 'SDM Office' },
  { code: 'UP', name: 'Uttar Pradesh', portalUrl: 'https://edistrict.up.gov.in/', platformFee: 49, baseFeeOverride: 10, processingTime: '10-15 days', department: 'Tehsildar' },
  { code: 'TN', name: 'Tamil Nadu', portalUrl: 'https://www.tnesevai.tn.gov.in/', platformFee: 49, baseFeeOverride: 12, processingTime: '8-14 days', department: 'Revenue Department' },
  { code: 'GJ', name: 'Gujarat', portalUrl: 'https://digitalgujarat.gov.in/', platformFee: 49, baseFeeOverride: 15, processingTime: '7-14 days', department: 'Revenue Department' },
];

const RTO_STATES: StatePortalSeed[] = [
  { code: 'MH', name: 'Maharashtra', portalUrl: 'https://parivahan.gov.in/', platformFee: 49, baseFeeOverride: 200, processingTime: '7-14 days', department: 'Regional Transport Office' },
  { code: 'KA', name: 'Karnataka', portalUrl: 'https://parivahan.gov.in/', platformFee: 49, baseFeeOverride: 200, processingTime: '7-14 days', department: 'Regional Transport Office' },
  { code: 'DL', name: 'Delhi', portalUrl: 'https://parivahan.gov.in/', platformFee: 49, baseFeeOverride: 200, processingTime: '5-10 days', department: 'Regional Transport Office' },
  { code: 'UP', name: 'Uttar Pradesh', portalUrl: 'https://parivahan.gov.in/', platformFee: 49, baseFeeOverride: 180, processingTime: '10-15 days', department: 'Regional Transport Office' },
];

function applicantFields(extra: FormFieldSeed[] = []): FormFieldSeed[] {
  return [
    { label: 'Applicant Full Name', key: 'applicant_name', type: 'TEXT', required: true },
    { label: 'Mobile Number', key: 'mobile_number', type: 'PHONE', required: true },
    { label: 'Email Address', key: 'email', type: 'EMAIL', required: false },
    ...extra,
  ];
}

function certificateSub(
  partial: Omit<SubServiceSeed, 'formFields' | 'documents' | 'requiresState' | 'defaultPlatformFee'> & {
    formFields?: FormFieldSeed[];
    documents?: string[];
    requiresState?: boolean;
    statePortals?: StatePortalSeed[];
  },
): SubServiceSeed {
  return {
    requiresState: partial.requiresState ?? true,
    defaultPlatformFee: 49,
    statePortals: partial.statePortals ?? COMMON_STATES,
    formFields: partial.formFields ?? applicantFields([
      { label: 'Residential Address', key: 'address', type: 'TEXTAREA', required: true },
    ]),
    documents: partial.documents ?? ['Aadhaar Card', 'Address Proof', 'Passport Size Photo'],
    ...partial,
  };
}

export const GOVERNMENT_SERVICES_CATALOG: MainServiceSeed[] = [
  {
    slug: 'identity-kyc',
    name: 'Identity & KYC',
    description: 'Aadhaar, PAN, Voter ID and identity verification services',
    sortOrder: 1,
    subServices: [
      {
        slug: 'pan-card',
        name: 'PAN Card',
        description: 'Apply for new PAN or correction',
        displayName: 'PAN Card Application',
        shortDescription: 'Apply for a new PAN or update existing PAN details',
        richDescription: 'Apply for a Permanent Account Number (PAN) through NSDL or UTIITSL. Cybersave assists with document preparation and guided submission.',
        instructions: 'Keep identity proof and address proof ready. For corrections, keep your existing PAN card handy.',
        processingTime: '5-7 working days',
        department: 'Income Tax Department',
        baseFee: 107,
        serviceFee: 199,
        requiresState: false,
        defaultPortalUrl: 'https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html',
        defaultPlatformFee: 49,
        manualInstructions: 'Complete the application on the official NSDL portal and save your acknowledgment number.',
        formFields: [
          { label: 'Full Name (as per Aadhaar)', key: 'full_name', type: 'TEXT', required: true },
          { label: 'Date of Birth', key: 'date_of_birth', type: 'DATE', required: true },
          { label: 'Mobile Number', key: 'mobile_number', type: 'PHONE', required: true },
          { label: 'Email Address', key: 'email', type: 'EMAIL', required: true },
          { label: "Father's Name", key: 'father_name', type: 'TEXT', required: true },
        ],
        documents: ['Aadhaar Card', 'Passport Size Photo', 'Signature Scan'],
      },
      {
        slug: 'aadhaar-update',
        name: 'Aadhaar Update',
        description: 'Update address, mobile or other Aadhaar details',
        displayName: 'Aadhaar Update / Correction',
        shortDescription: 'Update Aadhaar address, mobile number or demographic details',
        richDescription: 'Request corrections or updates to your Aadhaar through UIDAI authorized channels.',
        instructions: 'Use your registered mobile number for OTP verification on the UIDAI portal.',
        processingTime: '3-10 working days',
        department: 'UIDAI',
        baseFee: 50,
        serviceFee: 149,
        requiresState: false,
        defaultPortalUrl: 'https://myaadhaar.uidai.gov.in/',
        defaultPlatformFee: 39,
        manualInstructions: 'Login with your Aadhaar on the official UIDAI portal to update details.',
        formFields: [
          { label: 'Aadhaar Number', key: 'aadhaar_number', type: 'TEXT', required: true },
          { label: 'Update Type', key: 'update_type', type: 'TEXT', required: true, placeholder: 'Address / Mobile / Name' },
          { label: 'Registered Mobile', key: 'mobile_number', type: 'PHONE', required: true },
        ],
        documents: ['Aadhaar Card', 'Address Proof (if updating address)'],
      },
      {
        slug: 'voter-id',
        name: 'Voter ID',
        description: 'Apply for new Voter ID or correction',
        displayName: 'Voter ID (EPIC) Application',
        shortDescription: 'Register as a voter or update your Electoral Photo Identity Card',
        richDescription: 'Apply for a new Voter ID or request corrections through the National Voters Service Portal.',
        instructions: 'Ensure you are 18 years or above and have address proof for the constituency.',
        processingTime: '15-30 days',
        department: 'Election Commission of India',
        baseFee: 0,
        serviceFee: 149,
        requiresState: false,
        defaultPortalUrl: 'https://voters.eci.gov.in/',
        defaultPlatformFee: 49,
        manualInstructions: 'Complete Form 6 on the NVSP portal for new registration.',
        formFields: applicantFields([
          { label: 'Date of Birth', key: 'date_of_birth', type: 'DATE', required: true },
          { label: 'Assembly Constituency', key: 'constituency', type: 'TEXT', required: true },
          { label: 'Permanent Address', key: 'address', type: 'TEXTAREA', required: true },
        ]),
        documents: ['Aadhaar Card', 'Address Proof', 'Passport Size Photo'],
      },
    ],
  },
  {
    slug: 'certificates',
    name: 'Government Certificates',
    description: 'Income, caste, domicile, EWS and other official certificates',
    sortOrder: 2,
    subServices: [
      certificateSub({
        slug: 'income-certificate',
        name: 'Income Certificate',
        description: 'Proof of annual family income',
        displayName: 'Income Certificate',
        shortDescription: 'Official proof of annual income for scholarships and schemes',
        richDescription: 'Income certificate is required for scholarships, fee concessions, and government welfare schemes.',
        instructions: 'Provide accurate family income details. False information may lead to rejection.',
        processingTime: '7-15 days',
        department: 'Revenue / Tehsildar',
        baseFee: 15,
        serviceFee: 249,
        manualInstructions: 'Select your state portal and apply with income proof documents.',
        formFields: applicantFields([
          { label: 'Annual Family Income (₹)', key: 'annual_income', type: 'NUMBER', required: true },
          { label: 'Purpose of Certificate', key: 'purpose', type: 'TEXT', required: true },
          { label: "Father / Guardian Name", key: 'guardian_name', type: 'TEXT', required: true },
          { label: 'Residential Address', key: 'address', type: 'TEXTAREA', required: true },
        ]),
        documents: ['Aadhaar Card', 'Ration Card / Income Proof', 'Passport Size Photo'],
      }),
      certificateSub({
        slug: 'caste-certificate',
        name: 'Caste Certificate',
        description: 'SC/ST/OBC caste certificate',
        displayName: 'Caste Certificate',
        shortDescription: 'Caste certificate for reservations and welfare schemes',
        richDescription: 'Apply for Scheduled Caste, Scheduled Tribe or OBC certificate through your state e-District portal.',
        instructions: 'Parent caste certificate or school records may be required as supporting proof.',
        processingTime: '10-21 days',
        department: 'Revenue Department',
        baseFee: 20,
        serviceFee: 299,
        formFields: applicantFields([
          { label: 'Caste Category', key: 'caste_category', type: 'TEXT', required: true, placeholder: 'SC / ST / OBC' },
          { label: "Father's Name", key: 'father_name', type: 'TEXT', required: true },
          { label: 'Permanent Address', key: 'address', type: 'TEXTAREA', required: true },
        ]),
        documents: ['Aadhaar', 'Parent Caste Certificate or School Record', 'Address Proof'],
      }),
      certificateSub({
        slug: 'domicile-certificate',
        name: 'Domicile Certificate',
        description: 'State domicile / residence proof',
        displayName: 'Domicile / Residence Certificate',
        shortDescription: 'Proof of residence in a state for education and government jobs',
        richDescription: 'Domicile certificate confirms you are a resident of a particular state.',
        instructions: 'Residence duration requirements vary by state (typically 3-15 years).',
        processingTime: '7-15 days',
        department: 'Revenue Department',
        baseFee: 18,
        serviceFee: 249,
        formFields: applicantFields([
          { label: 'Years of Residence', key: 'years_residence', type: 'NUMBER', required: true },
          { label: 'Current Address', key: 'address', type: 'TEXTAREA', required: true },
        ]),
        documents: ['Aadhaar', 'Address Proof (5+ years)', 'Birth Certificate'],
      }),
      certificateSub({
        slug: 'ews-certificate',
        name: 'EWS Certificate',
        description: 'Economically Weaker Section certificate',
        displayName: 'EWS Certificate',
        shortDescription: 'Certificate for Economically Weaker Section reservation',
        richDescription: 'EWS certificate is required for reservation under the economically weaker section category.',
        instructions: 'Income and asset limits apply as per central and state rules.',
        processingTime: '7-14 days',
        department: 'Revenue Department',
        baseFee: 15,
        serviceFee: 249,
        formFields: applicantFields([
          { label: 'Annual Income (₹)', key: 'annual_income', type: 'NUMBER', required: true },
          { label: 'Residential Address', key: 'address', type: 'TEXTAREA', required: true },
        ]),
        documents: ['Aadhaar', 'Income Affidavit', 'Property Details Declaration'],
      }),
      certificateSub({
        slug: 'character-certificate',
        name: 'Character Certificate',
        description: 'Police / character verification certificate',
        displayName: 'Character Certificate',
        shortDescription: 'Character verification for jobs, visas and admissions',
        richDescription: 'Character certificate issued by police or revenue authorities for employment and travel.',
        instructions: 'May require police verification depending on state rules.',
        processingTime: '7-21 days',
        department: 'Police / Revenue',
        baseFee: 25,
        serviceFee: 299,
        formFields: applicantFields([
          { label: 'Purpose', key: 'purpose', type: 'TEXT', required: true, placeholder: 'Job / Visa / Admission' },
          { label: 'Permanent Address', key: 'address', type: 'TEXTAREA', required: true },
        ]),
        documents: ['Aadhaar', 'Address Proof', 'Passport Size Photo'],
      }),
      certificateSub({
        slug: 'solvency-certificate',
        name: 'Solvency Certificate',
        description: 'Proof of financial solvency',
        displayName: 'Solvency Certificate',
        shortDescription: 'Financial solvency proof for tenders and contracts',
        richDescription: 'Solvency certificate confirms financial capability for government tenders and contracts.',
        instructions: 'Bank statements or CA certificate may be required.',
        processingTime: '5-10 days',
        department: 'Revenue Department',
        baseFee: 30,
        serviceFee: 349,
        formFields: applicantFields([
          { label: 'Purpose', key: 'purpose', type: 'TEXT', required: true },
          { label: 'Estimated Net Worth (₹)', key: 'net_worth', type: 'NUMBER', required: true },
        ]),
        documents: ['Aadhaar', 'Bank Statement (6 months)', 'ITR / CA Certificate'],
      }),
      certificateSub({
        slug: 'nativity-certificate',
        name: 'Nativity Certificate',
        description: 'Proof of birthplace / native place',
        displayName: 'Nativity Certificate',
        shortDescription: 'Certificate confirming place of birth or native place',
        richDescription: 'Nativity certificate is required for certain government jobs and educational admissions.',
        instructions: 'Birth record or school leaving certificate helps processing.',
        processingTime: '7-14 days',
        department: 'Revenue Department',
        baseFee: 15,
        serviceFee: 249,
        formFields: applicantFields([
          { label: 'Place of Birth', key: 'place_of_birth', type: 'TEXT', required: true },
          { label: 'Native Village / Town', key: 'native_place', type: 'TEXT', required: true },
        ]),
        documents: ['Aadhaar', 'Birth Certificate', 'Address Proof'],
      }),
    ],
  },
  {
    slug: 'civil-records',
    name: 'Civil Records',
    description: 'Birth, death and marriage registration certificates',
    sortOrder: 3,
    subServices: [
      certificateSub({
        slug: 'birth-certificate',
        name: 'Birth Certificate',
        description: 'Apply for birth certificate',
        displayName: 'Birth Certificate',
        shortDescription: 'Official birth registration certificate',
        richDescription: 'Apply for a birth certificate from the municipal corporation or registrar office.',
        instructions: 'Hospital birth record or old certificate helps for faster processing.',
        processingTime: '5-10 days',
        department: 'Municipal Corporation / Registrar',
        baseFee: 25,
        serviceFee: 199,
        formFields: [
          { label: 'Child Full Name', key: 'child_name', type: 'TEXT', required: true },
          { label: 'Date of Birth', key: 'date_of_birth', type: 'DATE', required: true },
          { label: 'Place of Birth', key: 'place_of_birth', type: 'TEXT', required: true },
          { label: "Father's Name", key: 'father_name', type: 'TEXT', required: true },
          { label: "Mother's Name", key: 'mother_name', type: 'TEXT', required: true },
          { label: 'Applicant Mobile', key: 'mobile_number', type: 'PHONE', required: true },
        ],
        documents: ['Hospital Birth Record', 'Parent Aadhaar', 'Address Proof'],
      }),
      certificateSub({
        slug: 'death-certificate',
        name: 'Death Certificate',
        description: 'Apply for death certificate',
        displayName: 'Death Certificate',
        shortDescription: 'Official death registration certificate',
        richDescription: 'Register a death and obtain an official death certificate from the local registrar.',
        instructions: 'Death must be registered within the prescribed timeline as per state rules.',
        processingTime: '5-10 days',
        department: 'Municipal Corporation / Registrar',
        baseFee: 25,
        serviceFee: 199,
        formFields: [
          { label: 'Deceased Full Name', key: 'deceased_name', type: 'TEXT', required: true },
          { label: 'Date of Death', key: 'date_of_death', type: 'DATE', required: true },
          { label: 'Place of Death', key: 'place_of_death', type: 'TEXT', required: true },
          { label: 'Applicant Name', key: 'applicant_name', type: 'TEXT', required: true },
          { label: 'Relation to Deceased', key: 'relation', type: 'TEXT', required: true },
          { label: 'Applicant Mobile', key: 'mobile_number', type: 'PHONE', required: true },
        ],
        documents: ['Hospital Death Record', 'Applicant Aadhaar', 'Address Proof'],
      }),
      certificateSub({
        slug: 'marriage-certificate',
        name: 'Marriage Certificate',
        description: 'Register marriage and obtain certificate',
        displayName: 'Marriage Registration Certificate',
        shortDescription: 'Official marriage registration certificate',
        richDescription: 'Register your marriage under the Special Marriage Act or Hindu Marriage Act and obtain certificate.',
        instructions: 'Both spouses must provide identity and address proof.',
        processingTime: '7-15 days',
        department: 'Registrar of Marriages',
        baseFee: 50,
        serviceFee: 249,
        formFields: [
          { label: 'Husband Full Name', key: 'husband_name', type: 'TEXT', required: true },
          { label: 'Wife Full Name', key: 'wife_name', type: 'TEXT', required: true },
          { label: 'Date of Marriage', key: 'marriage_date', type: 'DATE', required: true },
          { label: 'Place of Marriage', key: 'marriage_place', type: 'TEXT', required: true },
          { label: 'Contact Mobile', key: 'mobile_number', type: 'PHONE', required: true },
        ],
        documents: ['Aadhaar (Both Spouses)', 'Marriage Invitation / Photos', 'Address Proof'],
      }),
    ],
  },
  {
    slug: 'transport-rto',
    name: 'Transport & RTO',
    description: 'Driving licence, vehicle registration and Parivahan services',
    sortOrder: 4,
    subServices: [
      {
        slug: 'driving-licence-renewal',
        name: 'Driving Licence Renewal',
        description: 'Renew expired or expiring driving licence',
        displayName: 'Driving Licence Renewal',
        shortDescription: 'Renew your driving licence online via Parivahan',
        richDescription: 'Renew your driving licence before expiry through the official Parivahan Sewa portal.',
        instructions: 'Keep existing DL, Aadhaar and mobile number ready for OTP.',
        processingTime: '7-14 days',
        department: 'Ministry of Road Transport',
        baseFee: 200,
        serviceFee: 299,
        requiresState: true,
        defaultPortalUrl: 'https://parivahan.gov.in/',
        defaultPlatformFee: 49,
        statePortals: RTO_STATES,
        manualInstructions: 'Login to Parivahan Sewa, select DL renewal and complete payment.',
        formFields: applicantFields([
          { label: 'Driving Licence Number', key: 'dl_number', type: 'TEXT', required: true },
          { label: 'Date of Birth', key: 'date_of_birth', type: 'DATE', required: true },
        ]),
        documents: ['Existing Driving Licence', 'Aadhaar Card', 'Passport Size Photo'],
      },
      {
        slug: 'learners-licence',
        name: "Learner's Licence",
        description: 'Apply for learner driving licence',
        displayName: "Learner's Licence Application",
        shortDescription: 'Apply for a new learner driving licence',
        richDescription: 'Apply for a learner licence to begin driving training on public roads.',
        instructions: 'Minimum age 18 for private vehicles. Online test may be required.',
        processingTime: '3-7 days',
        department: 'Regional Transport Office',
        baseFee: 150,
        serviceFee: 249,
        requiresState: true,
        defaultPortalUrl: 'https://parivahan.gov.in/',
        defaultPlatformFee: 49,
        statePortals: RTO_STATES,
        formFields: applicantFields([
          { label: 'Date of Birth', key: 'date_of_birth', type: 'DATE', required: true },
          { label: 'Vehicle Class', key: 'vehicle_class', type: 'TEXT', required: true, placeholder: 'LMV / MCWG' },
          { label: 'Residential Address', key: 'address', type: 'TEXTAREA', required: true },
        ]),
        documents: ['Aadhaar Card', 'Address Proof', 'Passport Size Photo', 'Medical Certificate (if applicable)'],
      },
      {
        slug: 'vehicle-registration',
        name: 'Vehicle Registration',
        description: 'New vehicle registration',
        displayName: 'New Vehicle Registration',
        shortDescription: 'Register a newly purchased vehicle',
        richDescription: 'Complete registration of a new vehicle through the RTO Parivahan portal.',
        instructions: 'Dealer invoice and insurance documents are required.',
        processingTime: '7-15 days',
        department: 'Regional Transport Office',
        baseFee: 600,
        serviceFee: 499,
        requiresState: true,
        defaultPortalUrl: 'https://parivahan.gov.in/',
        defaultPlatformFee: 49,
        statePortals: RTO_STATES,
        formFields: applicantFields([
          { label: 'Vehicle Class', key: 'vehicle_class', type: 'TEXT', required: true },
          { label: 'Chassis Number', key: 'chassis_number', type: 'TEXT', required: true },
          { label: 'Engine Number', key: 'engine_number', type: 'TEXT', required: true },
        ]),
        documents: ['Invoice / Sale Certificate', 'Insurance Copy', 'Aadhaar', 'PUC (if applicable)'],
      },
      {
        slug: 'duplicate-rc',
        name: 'Duplicate RC',
        description: 'Duplicate Registration Certificate',
        displayName: 'Duplicate Registration Certificate',
        shortDescription: 'Apply for duplicate vehicle RC',
        richDescription: 'Obtain a duplicate Registration Certificate if original is lost or damaged.',
        instructions: 'FIR copy required if RC is lost or stolen.',
        processingTime: '7-14 days',
        department: 'Regional Transport Office',
        baseFee: 300,
        serviceFee: 349,
        requiresState: true,
        defaultPortalUrl: 'https://parivahan.gov.in/',
        defaultPlatformFee: 49,
        statePortals: RTO_STATES,
        formFields: applicantFields([
          { label: 'Registration Number', key: 'registration_number', type: 'TEXT', required: true },
          { label: 'Reason for Duplicate', key: 'reason', type: 'TEXT', required: true, placeholder: 'Lost / Damaged' },
        ]),
        documents: ['Aadhaar', 'FIR Copy (if lost)', 'Insurance Copy'],
      },
    ],
  },
  {
    slug: 'social-welfare',
    name: 'Social Welfare',
    description: 'Pension, disability and senior citizen welfare schemes',
    sortOrder: 5,
    subServices: [
      certificateSub({
        slug: 'senior-citizen-certificate',
        name: 'Senior Citizen Certificate',
        description: 'Certificate for citizens aged 60 and above',
        displayName: 'Senior Citizen Certificate',
        shortDescription: 'Certificate for senior citizen benefits and concessions',
        richDescription: 'Obtain senior citizen certificate for railway concessions, tax benefits and welfare schemes.',
        instructions: 'Age proof such as Aadhaar or birth certificate is mandatory.',
        processingTime: '5-10 days',
        department: 'Social Welfare Department',
        baseFee: 10,
        serviceFee: 199,
        formFields: applicantFields([
          { label: 'Date of Birth', key: 'date_of_birth', type: 'DATE', required: true },
          { label: 'Residential Address', key: 'address', type: 'TEXTAREA', required: true },
        ]),
        documents: ['Aadhaar', 'Birth Certificate / Age Proof', 'Passport Size Photo'],
      }),
      certificateSub({
        slug: 'disability-certificate',
        name: 'Disability Certificate',
        description: 'UDID / disability certificate',
        displayName: 'Disability Certificate (UDID)',
        shortDescription: 'Certificate of disability for welfare benefits',
        richDescription: 'Apply for disability certificate through the UDID portal or designated medical authority.',
        instructions: 'Medical assessment may be required at a government hospital.',
        processingTime: '15-30 days',
        department: 'Department of Empowerment of Persons with Disabilities',
        baseFee: 0,
        serviceFee: 249,
        requiresState: false,
        defaultPortalUrl: 'https://www.swavlambancard.gov.in/',
        formFields: applicantFields([
          { label: 'Type of Disability', key: 'disability_type', type: 'TEXT', required: true },
          { label: 'Percentage of Disability', key: 'disability_percentage', type: 'NUMBER', required: false },
          { label: 'Residential Address', key: 'address', type: 'TEXTAREA', required: true },
        ]),
        documents: ['Aadhaar', 'Medical Assessment Report', 'Passport Size Photo'],
      }),
      certificateSub({
        slug: 'widow-pension',
        name: 'Widow Pension',
        description: 'Widow pension scheme application',
        displayName: 'Widow Pension Application',
        shortDescription: 'Apply for state widow pension scheme',
        richDescription: 'Apply for monthly pension under state widow pension welfare schemes.',
        instructions: 'Income and age criteria apply as per state scheme rules.',
        processingTime: '15-30 days',
        department: 'Social Welfare Department',
        baseFee: 0,
        serviceFee: 199,
        formFields: applicantFields([
          { label: 'Husband Name (Deceased)', key: 'husband_name', type: 'TEXT', required: true },
          { label: 'Date of Death of Spouse', key: 'spouse_death_date', type: 'DATE', required: true },
          { label: 'Annual Income (₹)', key: 'annual_income', type: 'NUMBER', required: true },
          { label: 'Bank Account Number', key: 'bank_account', type: 'TEXT', required: true },
        ]),
        documents: ['Aadhaar', 'Death Certificate of Spouse', 'Bank Passbook', 'Income Proof'],
      }),
      {
        slug: 'pm-awas-yojna',
        name: 'PM Awas Yojna',
        description: 'Pradhan Mantri Awas Yojana housing scheme',
        displayName: 'Pradhan Mantri Awas Yojana (PMAY)',
        shortDescription: 'Affordable housing for rural and urban households',
        richDescription:
          'Apply under PMAY for credit-linked subsidy and assistance to build or upgrade a pucca house with basic amenities.',
        instructions:
          'Ensure Aadhaar-linked bank account and property/income details match scheme eligibility criteria.',
        processingTime: '30-60 days',
        department: 'Ministry of Housing & Urban Affairs',
        baseFee: 0,
        serviceFee: 199,
        requiresState: true,
        defaultPortalUrl: 'https://pmaymis.gov.in/',
        defaultPlatformFee: 49,
        statePortals: COMMON_STATES.map(s => ({
          ...s,
          portalUrl: 'https://pmaymis.gov.in/',
          department: 'Housing & Urban Development',
          processingTime: '30-60 days',
        })),
        formFields: applicantFields([
          { label: 'Annual Household Income (₹)', key: 'annual_income', type: 'NUMBER', required: true },
          { label: 'Preferred Housing Category', key: 'housing_category', type: 'DROPDOWN', required: true, placeholder: 'EWS / LIG / MIG' },
          { label: 'Current Address', key: 'address', type: 'TEXTAREA', required: true },
          { label: 'Bank Account Number', key: 'bank_account', type: 'TEXT', required: true },
          { label: 'IFSC Code', key: 'ifsc', type: 'TEXT', required: true },
        ]),
        documents: ['Aadhaar', 'Income Certificate', 'Bank Passbook', 'Passport Size Photo'],
      },
    ],
  },
  {
    slug: 'agriculture-rural',
    name: 'Agriculture & Rural',
    description: 'Farmer certificates, PM-Kisan and land records',
    sortOrder: 6,
    subServices: [
      certificateSub({
        slug: 'farmer-certificate',
        name: 'Farmer Certificate',
        description: 'Certificate for farmers',
        displayName: 'Farmer Certificate',
        shortDescription: 'Official farmer certificate for schemes and subsidies',
        richDescription: 'Farmer certificate is required for agricultural subsidies and crop insurance schemes.',
        instructions: 'Land ownership or cultivation proof may be required.',
        processingTime: '7-15 days',
        department: 'Agriculture Department',
        baseFee: 15,
        serviceFee: 249,
        formFields: applicantFields([
          { label: 'Land Survey Number', key: 'survey_number', type: 'TEXT', required: true },
          { label: 'Village / Tehsil', key: 'village', type: 'TEXT', required: true },
          { label: 'Crops Grown', key: 'crops', type: 'TEXT', required: false },
        ]),
        documents: ['Aadhaar', 'Land Records / 7-12 Extract', 'Passport Size Photo'],
      }),
      {
        slug: 'pm-kisan-registration',
        name: 'PM-Kisan Registration',
        description: 'PM-KISAN Samman Nidhi registration',
        displayName: 'PM-Kisan Samman Nidhi',
        shortDescription: 'Register for ₹6,000/year farmer income support',
        richDescription: 'Register under PM-KISAN to receive financial support for eligible farmer families.',
        instructions: 'Landholding and bank account details must match Aadhaar records.',
        processingTime: '15-30 days',
        department: 'Ministry of Agriculture',
        baseFee: 0,
        serviceFee: 149,
        requiresState: false,
        defaultPortalUrl: 'https://pmkisan.gov.in/',
        defaultPlatformFee: 39,
        formFields: applicantFields([
          { label: 'Aadhaar Number', key: 'aadhaar_number', type: 'TEXT', required: true },
          { label: 'Landholding Size (hectares)', key: 'land_size', type: 'NUMBER', required: true },
          { label: 'Bank Account Number', key: 'bank_account', type: 'TEXT', required: true },
          { label: 'IFSC Code', key: 'ifsc', type: 'TEXT', required: true },
        ]),
        documents: ['Aadhaar', 'Land Records', 'Bank Passbook'],
      },
      certificateSub({
        slug: 'land-records-extract',
        name: 'Land Records Extract',
        description: '7/12 or land record extract',
        displayName: 'Land Records Extract (7/12)',
        shortDescription: 'Official land record extract from revenue department',
        richDescription: 'Obtain certified copy of land records (7/12, Khatauni) from state revenue portal.',
        instructions: 'Survey number and village name must be accurate.',
        processingTime: '3-7 days',
        department: 'Revenue Department',
        baseFee: 30,
        serviceFee: 249,
        formFields: applicantFields([
          { label: 'Survey / Gat Number', key: 'survey_number', type: 'TEXT', required: true },
          { label: 'Village Name', key: 'village', type: 'TEXT', required: true },
          { label: 'Taluka / Tehsil', key: 'tehsil', type: 'TEXT', required: true },
        ]),
        documents: ['Aadhaar', 'Previous Land Record (if available)', 'Identity Proof'],
      }),
    ],
  },
  {
    slug: 'employment-labour',
    name: 'Employment & Labour',
    description: 'Labour cards, experience certificates and job-related documents',
    sortOrder: 7,
    subServices: [
      certificateSub({
        slug: 'labour-card',
        name: 'Labour Card',
        description: 'Unorganised worker registration',
        displayName: 'Labour Card / Worker Registration',
        shortDescription: 'Register as unorganised sector worker',
        richDescription: 'Register for e-Shram or state labour welfare board to access benefits.',
        instructions: 'Aadhaar-linked bank account is required for benefit transfers.',
        processingTime: '7-15 days',
        department: 'Ministry of Labour & Employment',
        baseFee: 0,
        serviceFee: 149,
        requiresState: false,
        defaultPortalUrl: 'https://eshram.gov.in/',
        formFields: applicantFields([
          { label: 'Occupation', key: 'occupation', type: 'TEXT', required: true },
          { label: 'Years of Experience', key: 'experience_years', type: 'NUMBER', required: false },
          { label: 'Bank Account Number', key: 'bank_account', type: 'TEXT', required: true },
        ]),
        documents: ['Aadhaar', 'Bank Passbook', 'Passport Size Photo'],
      }),
      certificateSub({
        slug: 'experience-certificate',
        name: 'Experience Certificate',
        description: 'Work experience verification',
        displayName: 'Experience Certificate',
        shortDescription: 'Official work experience certificate',
        richDescription: 'Apply for experience certificate through employer or labour department verification.',
        instructions: 'Previous employer details help expedite verification.',
        processingTime: '5-10 days',
        department: 'Labour Department',
        baseFee: 20,
        serviceFee: 199,
        formFields: applicantFields([
          { label: 'Employer / Organisation Name', key: 'employer_name', type: 'TEXT', required: true },
          { label: 'Designation', key: 'designation', type: 'TEXT', required: true },
          { label: 'Employment Period', key: 'employment_period', type: 'TEXT', required: true, placeholder: 'Jan 2020 - Mar 2024' },
        ]),
        documents: ['Aadhaar', 'Previous Offer Letter / Payslips', 'Passport Size Photo'],
      }),
      certificateSub({
        slug: 'government-job-noc',
        name: 'Government Job NOC',
        description: 'No Objection Certificate for job',
        displayName: 'NOC for Government Job',
        shortDescription: 'No Objection Certificate from current employer',
        richDescription: 'Apply for NOC required when joining a government position from private employment.',
        instructions: 'Current employer NOC format may vary by recruiting department.',
        processingTime: '7-14 days',
        department: 'Recruiting Department',
        baseFee: 25,
        serviceFee: 249,
        formFields: applicantFields([
          { label: 'Current Employer', key: 'employer_name', type: 'TEXT', required: true },
          { label: 'Post Applied For', key: 'post_applied', type: 'TEXT', required: true },
          { label: 'Recruiting Agency', key: 'recruiting_agency', type: 'TEXT', required: true },
        ]),
        documents: ['Aadhaar', 'Offer Letter / Application Copy', 'Employer NOC Template'],
      }),
    ],
  },
  {
    slug: 'education-services',
    name: 'Education Services',
    description: 'Bonafide, transfer certificate and scholarship applications',
    sortOrder: 8,
    subServices: [
      certificateSub({
        slug: 'bonafide-certificate',
        name: 'Bonafide Certificate',
        description: 'Student bonafide certificate',
        displayName: 'Bonafide Certificate',
        shortDescription: 'Certificate confirming student enrollment',
        richDescription: 'Bonafide certificate confirms current enrollment in an educational institution.',
        instructions: 'Institution details must match official records.',
        processingTime: '3-7 days',
        department: 'Education Department',
        baseFee: 10,
        serviceFee: 149,
        requiresState: true,
        manualInstructions:
          'Select your state and apply through the official education or e-District portal.',
        formFields: [
          { label: 'Student Full Name', key: 'student_name', type: 'TEXT', required: true },
          { label: 'Institution Name', key: 'institution_name', type: 'TEXT', required: true },
          { label: 'Class / Course', key: 'class_course', type: 'TEXT', required: true },
          { label: 'Roll Number', key: 'roll_number', type: 'TEXT', required: true },
          { label: 'Parent Mobile', key: 'mobile_number', type: 'PHONE', required: true },
        ],
        documents: ['Student ID Card', 'Previous Marksheet', 'Parent Aadhaar'],
      }),
      certificateSub({
        slug: 'transfer-certificate',
        name: 'Transfer Certificate',
        description: 'School / college transfer certificate',
        displayName: 'Transfer Certificate (TC)',
        shortDescription: 'Transfer certificate for changing institution',
        richDescription: 'Apply for TC when transferring between schools or colleges.',
        instructions: 'Clear pending dues at current institution before applying.',
        processingTime: '5-10 days',
        department: 'Education Department',
        baseFee: 15,
        serviceFee: 199,
        requiresState: true,
        manualInstructions:
          'Select your state and apply through the official education or e-District portal.',
        formFields: [
          { label: 'Student Full Name', key: 'student_name', type: 'TEXT', required: true },
          { label: 'Current Institution', key: 'current_institution', type: 'TEXT', required: true },
          { label: 'New Institution', key: 'new_institution', type: 'TEXT', required: true },
          { label: 'Reason for Transfer', key: 'reason', type: 'TEXT', required: true },
          { label: 'Parent Mobile', key: 'mobile_number', type: 'PHONE', required: true },
        ],
        documents: ['Student Aadhaar / Birth Certificate', 'Previous TC (if any)', 'Parent ID Proof'],
      }),
      certificateSub({
        slug: 'scholarship-application',
        name: 'Scholarship Application',
        description: 'Government scholarship application assistance',
        displayName: 'Scholarship Application',
        shortDescription: 'Assistance for National / State scholarship schemes',
        richDescription: 'Apply for post-matric, pre-matric and merit scholarships through National Scholarship Portal.',
        instructions: 'Income and caste certificates may be required for eligibility.',
        processingTime: '15-30 days',
        department: 'Ministry of Education',
        baseFee: 0,
        serviceFee: 199,
        requiresState: false,
        defaultPortalUrl: 'https://scholarships.gov.in/',
        formFields: [
          { label: 'Student Full Name', key: 'student_name', type: 'TEXT', required: true },
          { label: 'Institution Name', key: 'institution_name', type: 'TEXT', required: true },
          { label: 'Course / Class', key: 'class_course', type: 'TEXT', required: true },
          { label: 'Annual Family Income (₹)', key: 'annual_income', type: 'NUMBER', required: true },
          { label: 'Mobile Number', key: 'mobile_number', type: 'PHONE', required: true },
        ],
        documents: ['Aadhaar', 'Income Certificate', 'Caste Certificate (if applicable)', 'Previous Marksheet'],
      }),
    ],
  },
];
