import type { GovernmentScheme } from './schemes.api';

/** Used when GET /schemes is empty or the hosted API has not been redeployed yet. */
export const FALLBACK_GOVERNMENT_SCHEMES: GovernmentScheme[] = [
  {
    id: 'pmay',
    name: 'Pradhan Mantri Awas Yojana (PMAY)',
    slug: 'pmay',
    ministry: 'Ministry of Housing and Urban Affairs',
    category: 'Housing',
    description:
      'Interest subsidy on home loans and affordable pucca housing support for eligible families in rural and urban India.',
    whoCanApply: 'EWS / LIG / MIG households',
    eligibility:
      'Households without a pucca house in India who meet income and ownership rules of PMAY (Urban or Gramin).',
    documentsRequired: ['Aadhaar card', 'Income certificate', 'Bank passbook', 'Passport-size photo'],
    officialPortalUrl: 'https://pmaymis.gov.in/',
    officialPortalLabel: 'Official Portal',
    displayOrder: 1,
  },
  {
    id: 'pm-kisan',
    name: 'PM-KISAN Samman Nidhi',
    slug: 'pm-kisan',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    category: 'Agriculture',
    description: '₹6,000 per year in three instalments paid directly to eligible farmer families.',
    whoCanApply: 'Small and marginal farmers',
    eligibility:
      'Landholding farmer families with cultivable land as per PM-KISAN scheme rules, excluding ineligible categories notified by the government.',
    documentsRequired: ['Aadhaar card', 'Land records', 'Bank passbook', 'Farmer ID / registration'],
    officialPortalUrl: 'https://pmkisan.gov.in/',
    officialPortalLabel: 'Official Portal',
    displayOrder: 2,
  },
  {
    id: 'pm-jay',
    name: 'Ayushman Bharat — PM-JAY',
    slug: 'pm-jay',
    ministry: 'Ministry of Health & Family Welfare',
    category: 'Health',
    description:
      'Health cover up to ₹5 lakh per family per year for secondary and tertiary hospitalisation.',
    whoCanApply: 'SECC / Ayushman-eligible families',
    eligibility:
      'Families identified under SECC / Ayushman Bharat eligibility criteria in the beneficiary database.',
    documentsRequired: ['Aadhaar card', 'Ration card', 'Family details'],
    officialPortalUrl: 'https://pmjay.gov.in/',
    officialPortalLabel: 'Official Portal',
    displayOrder: 3,
  },
  {
    id: 'pm-ujjwala',
    name: 'Pradhan Mantri Ujjwala Yojana',
    slug: 'pm-ujjwala',
    ministry: 'Ministry of Petroleum and Natural Gas',
    category: 'Social Welfare',
    description: 'Free LPG connection with financial assistance for eligible women from poor households.',
    whoCanApply: 'Adult women from BPL households',
    eligibility: 'Adult woman from a poor household without an existing LPG connection.',
    documentsRequired: ['Aadhaar card', 'BPL / ration card', 'Bank passbook', 'Passport-size photo'],
    officialPortalUrl: 'https://pmuy.gov.in/',
    officialPortalLabel: 'Official Portal',
    displayOrder: 4,
  },
  {
    id: 'nsp',
    name: 'National Scholarship Portal',
    slug: 'nsp',
    ministry: 'Ministry of Education',
    category: 'Education',
    description: 'Central and state scholarships for school, college and technical education students.',
    whoCanApply: 'Students',
    eligibility:
      'Students meeting income, merit and category criteria of the respective scholarship scheme.',
    documentsRequired: [
      'Aadhaar card',
      'Marksheets',
      'Income certificate',
      'Caste certificate (if applicable)',
      'Bank passbook',
    ],
    officialPortalUrl: 'https://scholarships.gov.in/',
    officialPortalLabel: 'Official Portal',
    displayOrder: 5,
  },
  {
    id: 'pm-svanidhi',
    name: 'PM SVANidhi',
    slug: 'pm-svanidhi',
    ministry: 'Ministry of Housing and Urban Affairs',
    category: 'Employment',
    description: 'Working capital loan up to ₹50,000 for street vendors with interest subsidy.',
    whoCanApply: 'Street vendors',
    eligibility: 'Street vendors vending in urban areas with valid identity or vending certificate.',
    documentsRequired: ['Aadhaar card', 'Vending certificate / identity proof', 'Bank passbook'],
    officialPortalUrl: 'https://pmsvanidhi.mohua.gov.in/',
    officialPortalLabel: 'Official Portal',
    displayOrder: 6,
  },
  {
    id: 'mudra',
    name: 'MUDRA Loan (PMMY)',
    slug: 'mudra',
    ministry: 'Ministry of Finance',
    category: 'Financial Inclusion',
    description: 'Collateral-free loans up to ₹10 lakh for micro and small enterprise activities.',
    whoCanApply: 'Micro & small entrepreneurs',
    eligibility: 'Non-corporate small business units and entrepreneurs seeking Shishu, Kishore or Tarun loans.',
    documentsRequired: ['Aadhaar card', 'PAN', 'Business proof', 'Bank statements'],
    officialPortalUrl: 'https://www.mudra.org.in/',
    officialPortalLabel: 'Official Portal',
    displayOrder: 7,
  },
  {
    id: 'apy',
    name: 'Atal Pension Yojana (APY)',
    slug: 'apy',
    ministry: 'Ministry of Finance',
    category: 'Social Welfare',
    description: 'Guaranteed minimum pension from ₹1,000 to ₹5,000 per month after 60 years of age.',
    whoCanApply: 'Indian citizens aged 18–40',
    eligibility: 'Indian citizens aged 18–40 with a savings bank or post office account.',
    documentsRequired: ['Aadhaar card', 'Bank / post office passbook', 'Mobile number'],
    officialPortalUrl: 'https://npscra.nsdl.co.in/scheme-details.php',
    officialPortalLabel: 'Official Portal',
    displayOrder: 8,
  },
  {
    id: 'pm-jdy',
    name: 'Pradhan Mantri Jan Dhan Yojana',
    slug: 'pm-jdy',
    ministry: 'Ministry of Finance',
    category: 'Financial Inclusion',
    description:
      'Zero-balance bank account with RuPay debit card, accident insurance and overdraft facility.',
    whoCanApply: 'Any unbanked Indian citizen',
    eligibility: 'Any Indian citizen without a bank account.',
    documentsRequired: ['Aadhaar card', 'Address proof', 'Passport-size photo'],
    officialPortalUrl: 'https://www.pmjdy.gov.in/',
    officialPortalLabel: 'Official Portal',
    displayOrder: 9,
  },
  {
    id: 'standup-india',
    name: 'Stand-Up India',
    slug: 'standup-india',
    ministry: 'Ministry of Finance',
    category: 'Women & Child',
    description: 'Bank loans between ₹10 lakh and ₹1 crore for SC/ST and women entrepreneurs.',
    whoCanApply: 'Women or SC/ST entrepreneurs',
    eligibility: 'Women or SC/ST entrepreneurs setting up greenfield enterprises.',
    documentsRequired: [
      'Aadhaar card',
      'PAN',
      'Caste certificate (if applicable)',
      'Project report',
      'Bank statements',
    ],
    officialPortalUrl: 'https://www.standupmitra.in/',
    officialPortalLabel: 'Official Portal',
    displayOrder: 10,
  },
  {
    id: 'pm-vishwakarma',
    name: 'PM Vishwakarma',
    slug: 'pm-vishwakarma',
    ministry: 'Ministry of Micro, Small and Medium Enterprises',
    category: 'Employment',
    description: 'Skill training, toolkit incentive and collateral-free credit support for artisans.',
    whoCanApply: 'Traditional artisans',
    eligibility: 'Traditional artisans and craftspeople in the 18 listed trades.',
    documentsRequired: ['Aadhaar card', 'Bank passbook', 'Trade / artisan details', 'Passport-size photo'],
    officialPortalUrl: 'https://pmvishwakarma.gov.in/',
    officialPortalLabel: 'Official Portal',
    displayOrder: 11,
  },
  {
    id: 'pm-fby',
    name: 'PM Fasal Bima Yojana',
    slug: 'pm-fby',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    category: 'Agriculture',
    description: 'Crop insurance at a low premium with timely claim settlement for notified crops.',
    whoCanApply: 'Farmers with notified crops',
    eligibility: 'Farmers growing notified crops in notified areas during the crop season.',
    documentsRequired: ['Aadhaar card', 'Land records', 'Bank passbook', 'Sowing details'],
    officialPortalUrl: 'https://pmfby.gov.in/',
    officialPortalLabel: 'Official Portal',
    displayOrder: 12,
  },
  {
    id: 'widow-pension',
    name: 'Widow Pension Scheme',
    slug: 'widow-pension',
    ministry: 'Ministry of Social Justice & Empowerment (State schemes)',
    category: 'Social Welfare',
    description:
      'Monthly financial assistance to eligible widows through state social welfare departments.',
    whoCanApply: 'Widows meeting state rules',
    eligibility:
      'Widows meeting age and income criteria as per the respective state NSAP / state pension rules.',
    documentsRequired: [
      'Aadhaar card',
      'Death certificate of spouse',
      'Income certificate',
      'Bank passbook',
      'Age proof',
    ],
    officialPortalUrl: 'https://nsap.nic.in/',
    officialPortalLabel: 'Official Portal',
    displayOrder: 13,
  },
  {
    id: 'kanya-vivah-bihar',
    name: 'Mukhyamantri Kanya Vivah Yojana (Bihar)',
    slug: 'kanya-vivah-bihar',
    ministry: 'Government of Bihar — Social Welfare Department',
    category: 'Women & Child',
    description: 'Financial assistance for marriage of daughters of eligible BPL families in Bihar.',
    whoCanApply: 'Bihar BPL families',
    eligibility: 'Resident of Bihar meeting income, age and documentation criteria of the scheme.',
    documentsRequired: [
      'Aadhaar card',
      'Residence proof',
      'Income / BPL proof',
      'Age proof of bride',
      'Marriage documents',
    ],
    officialPortalUrl: 'https://state.bihar.gov.in/socialwelfare/',
    officialPortalLabel: 'Official Portal',
    displayOrder: 14,
  },
  {
    id: 'ssy',
    name: 'Sukanya Samriddhi Yojana',
    slug: 'ssy',
    ministry: 'Ministry of Finance',
    category: 'Women & Child',
    description: 'High-interest small savings scheme for a girl child with tax benefits under 80C.',
    whoCanApply: 'Parents / guardians of a girl child',
    eligibility: 'Account for a girl child below 10 years; maximum two accounts per family.',
    documentsRequired: [
      'Aadhaar of guardian',
      'Birth certificate of girl child',
      'Address proof',
      'Passport-size photos',
    ],
    officialPortalUrl: 'https://www.india.gov.in/spotlight/sukanya-samriddhi-yojana',
    officialPortalLabel: 'Official Portal',
    displayOrder: 15,
  },
];

export function fallbackSchemes(category?: string) {
  if (!category || category === 'All') return FALLBACK_GOVERNMENT_SCHEMES;
  return FALLBACK_GOVERNMENT_SCHEMES.filter(scheme => scheme.category === category);
}

export function fallbackScheme(idOrSlug: string) {
  const key = idOrSlug.trim().toLowerCase();
  return FALLBACK_GOVERNMENT_SCHEMES.find(
    scheme => scheme.slug.toLowerCase() === key || scheme.id.toLowerCase() === key,
  );
}
