import type { AuditEventCategory, AuditLogEntry, AuditLogsStats } from '../types';

export const AUDIT_LOGS_STATS: AuditLogsStats = {
  totalEvents: 24582,
  loginActivities: 3124,
  documentActions: 18945,
  systemChanges: 513,
};

export const CATEGORY_OPTIONS: { value: AuditEventCategory; label: string }[] = [
  { value: 'login', label: 'Login Activities' },
  { value: 'document', label: 'Document Actions' },
  { value: 'system', label: 'System Changes' },
  { value: 'security', label: 'Security Events' },
  { value: 'user', label: 'User Management' },
];

export const USER_OPTIONS = [
  'Priya Sharma',
  'Rahul Verma',
  'Anjali Nair',
  'Suresh Reddy',
  'Kavita Joshi',
  'Manoj Kumar',
  'System',
];

export const DATE_RANGE_OPTIONS = [
  { value: '24h', label: 'Last 24 Hours' },
  { value: '7d', label: 'Last 7 Days' },
  { value: '30d', label: 'Last 30 Days' },
  { value: '90d', label: 'Last 90 Days' },
];

export const AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'LOG-90231',
    timestamp: '2026-08-06T21:42:18',
    userName: 'Priya Sharma',
    userRole: 'Admin',
    category: 'login',
    action: 'User Login',
    resource: 'Auth Service',
    ipAddress: '192.168.1.45',
    status: 'success',
  },
  {
    id: 'LOG-90230',
    timestamp: '2026-08-06T21:15:52',
    userName: 'Rahul Verma',
    userRole: 'Operator',
    category: 'document',
    action: 'Document Uploaded',
    resource: 'Aadhaar Card — CIT-00481',
    ipAddress: '192.168.1.52',
    status: 'success',
  },
  {
    id: 'LOG-90229',
    timestamp: '2026-08-06T20:58:03',
    userName: 'System',
    userRole: 'Automated',
    category: 'system',
    action: 'Backup Completed',
    resource: 'Database Backup',
    ipAddress: '10.0.0.1',
    status: 'success',
  },
  {
    id: 'LOG-90228',
    timestamp: '2026-08-06T20:41:37',
    userName: 'Suresh Reddy',
    userRole: 'Citizen',
    category: 'security',
    action: 'Failed Login Attempt',
    resource: 'Auth Service',
    ipAddress: '203.0.113.24',
    status: 'failed',
  },
  {
    id: 'LOG-90227',
    timestamp: '2026-08-06T19:53:11',
    userName: 'Anjali Nair',
    userRole: 'Supervisor',
    category: 'system',
    action: 'Service Configuration Updated',
    resource: 'PAN Card Service',
    ipAddress: '192.168.1.12',
    status: 'warning',
  },
  {
    id: 'LOG-90226',
    timestamp: '2026-08-06T19:20:44',
    userName: 'Kavita Joshi',
    userRole: 'Admin',
    category: 'user',
    action: 'Permission Changed',
    resource: 'User Role — Operator',
    ipAddress: '192.168.1.8',
    status: 'success',
  },
  {
    id: 'LOG-90225',
    timestamp: '2026-08-06T18:47:29',
    userName: 'Manoj Kumar',
    userRole: 'Operator',
    category: 'document',
    action: 'Document Rejected',
    resource: 'Income Certificate — CIT-00477',
    ipAddress: '192.168.1.63',
    status: 'failed',
  },
  {
    id: 'LOG-90224',
    timestamp: '2026-08-06T18:02:05',
    userName: 'System',
    userRole: 'Automated',
    category: 'system',
    action: 'Scheduled Maintenance',
    resource: 'Application Server',
    ipAddress: '10.0.0.5',
    status: 'warning',
  },
  {
    id: 'LOG-90223',
    timestamp: '2026-08-06T17:38:52',
    userName: 'Priya Sharma',
    userRole: 'Admin',
    category: 'user',
    action: 'New Operator Account Created',
    resource: 'User Management',
    ipAddress: '192.168.1.45',
    status: 'success',
  },
  {
    id: 'LOG-90222',
    timestamp: '2026-08-06T17:11:36',
    userName: 'Rahul Verma',
    userRole: 'Operator',
    category: 'login',
    action: 'Password Reset',
    resource: 'Auth Service',
    ipAddress: '192.168.1.52',
    status: 'success',
  },
  {
    id: 'LOG-90221',
    timestamp: '2026-08-06T16:44:19',
    userName: 'Anjali Nair',
    userRole: 'Supervisor',
    category: 'document',
    action: 'Bulk Document Export',
    resource: 'Applications Report',
    ipAddress: '192.168.1.12',
    status: 'success',
  },
  {
    id: 'LOG-90220',
    timestamp: '2026-08-06T16:09:47',
    userName: 'Suresh Reddy',
    userRole: 'Citizen',
    category: 'security',
    action: 'Session Timed Out',
    resource: 'Citizen Portal',
    ipAddress: '203.0.113.24',
    status: 'warning',
  },
  {
    id: 'LOG-90219',
    timestamp: '2026-08-06T15:32:58',
    userName: 'Kavita Joshi',
    userRole: 'Admin',
    category: 'system',
    action: 'Backup Restore Verified',
    resource: 'Database Backup',
    ipAddress: '192.168.1.8',
    status: 'success',
  },
  {
    id: 'LOG-90218',
    timestamp: '2026-08-06T14:58:03',
    userName: 'Manoj Kumar',
    userRole: 'Operator',
    category: 'login',
    action: 'Failed Login Attempt',
    resource: 'Auth Service',
    ipAddress: '192.168.1.63',
    status: 'failed',
  },
  {
    id: 'LOG-90217',
    timestamp: '2026-08-06T14:20:41',
    userName: 'System',
    userRole: 'Automated',
    category: 'document',
    action: 'Document Auto-Archived',
    resource: 'Completed Applications',
    ipAddress: '10.0.0.1',
    status: 'success',
  },
  {
    id: 'LOG-90216',
    timestamp: '2026-08-06T13:47:15',
    userName: 'Priya Sharma',
    userRole: 'Admin',
    category: 'security',
    action: 'API Key Rotated',
    resource: 'Payment Gateway',
    ipAddress: '192.168.1.45',
    status: 'success',
  },
];
