import type {
  ApplicationDetail,
  ApplicationSummary,
  ApplicationsStats,
  ChecklistItem,
  InternalNote,
  PaymentInformation,
  PipelineStage,
  SupportingDocument,
  TimelineEvent,
} from '../types';

export const APPLICATIONS_STATS: ApplicationsStats = {
  total: 12847,
  todayReceived: 1247,
  pendingReview: 342,
  inProcessing: 189,
  completedToday: 856,
};

export const PIPELINE_STAGES: PipelineStage[] = [
  { key: 'submitted', label: 'Submitted', count: 1247 },
  { key: 'under_review', label: 'Under Review', count: 342 },
  { key: 'action_required', label: 'Action Required', count: 48 },
  { key: 'processing', label: 'Processing', count: 189 },
  { key: 'approved', label: 'Approved', count: 214 },
  { key: 'completed', label: 'Completed', count: 856 },
];

export const CATEGORY_TABS = [
  'All Applications',
  'Aadhaar Services',
  'PAN Card',
  'Certificates',
  'Banking',
  'Insurance',
  'Utility',
  'Other',
] as const;

export const OPERATORS = ['Amit Kumar', 'Sunita Rao', 'Ravi Teja', 'Deepak Verma', 'Meena Iyer'];

export const APPLICATIONS: ApplicationSummary[] = [
  {
    id: 'APP-2026-8471',
    citizenId: 'CIT-00482',
    citizenName: 'Priya Sharma',
    citizenInitials: 'PS',
    service: 'Aadhaar Address Update',
    category: 'Aadhaar Services',
    priority: 'high',
    status: 'under_review',
    assignedOperator: 'Amit Kumar',
    centre: 'Banjara Hills Centre, Hyderabad',
    submittedAt: '2026-08-03T09:12:00',
    slaHours: 48,
    slaRemainingHours: 14,
    amount: 50,
  },
  {
    id: 'APP-2026-8470',
    citizenId: 'CIT-00481',
    citizenName: 'Rahul Verma',
    citizenInitials: 'RV',
    service: 'PAN Card - New',
    category: 'PAN Card',
    priority: 'medium',
    status: 'submitted',
    assignedOperator: null,
    centre: 'Kazipet Centre, Warangal',
    submittedAt: '2026-08-03T08:54:00',
    slaHours: 72,
    slaRemainingHours: 68,
    amount: 107,
  },
  {
    id: 'APP-2026-8469',
    citizenId: 'CIT-00480',
    citizenName: 'Anjali Nair',
    citizenInitials: 'AN',
    service: 'Birth Certificate',
    category: 'Certificates',
    priority: 'low',
    status: 'completed',
    assignedOperator: 'Sunita Rao',
    centre: 'Karimnagar Main Centre',
    submittedAt: '2026-08-03T08:31:00',
    slaHours: 24,
    slaRemainingHours: 0,
    amount: 50,
  },
  {
    id: 'APP-2026-8468',
    citizenId: 'CIT-00479',
    citizenName: 'Suresh Reddy',
    citizenInitials: 'SR',
    service: 'Income Certificate',
    category: 'Certificates',
    priority: 'medium',
    status: 'processing',
    assignedOperator: 'Ravi Teja',
    centre: 'Nizamabad Centre',
    submittedAt: '2026-08-03T08:02:00',
    slaHours: 24,
    slaRemainingHours: 6,
    amount: 30,
  },
  {
    id: 'APP-2026-8467',
    citizenId: 'CIT-00478',
    citizenName: 'Kavita Joshi',
    citizenInitials: 'KJ',
    service: 'Bank Account Opening',
    category: 'Banking',
    priority: 'low',
    status: 'rejected',
    assignedOperator: 'Deepak Verma',
    centre: 'Khammam Centre',
    submittedAt: '2026-08-03T07:45:00',
    slaHours: 48,
    slaRemainingHours: 0,
    amount: 0,
  },
  {
    id: 'APP-2026-8466',
    citizenId: 'CIT-00477',
    citizenName: 'Manoj Kumar',
    citizenInitials: 'MK',
    service: 'Passport Renewal',
    category: 'Other',
    priority: 'high',
    status: 'processing',
    assignedOperator: 'Amit Kumar',
    centre: 'Adilabad Centre',
    submittedAt: '2026-08-03T07:20:00',
    slaHours: 120,
    slaRemainingHours: 52,
    amount: 1500,
  },
  {
    id: 'APP-2026-8465',
    citizenId: 'CIT-00476',
    citizenName: 'Deepika Rao',
    citizenInitials: 'DR',
    service: 'Health Insurance Enrollment',
    category: 'Insurance',
    priority: 'medium',
    status: 'approved',
    assignedOperator: 'Meena Iyer',
    centre: 'Medak Centre',
    submittedAt: '2026-08-02T18:10:00',
    slaHours: 48,
    slaRemainingHours: 12,
    amount: 250,
  },
  {
    id: 'APP-2026-8464',
    citizenId: 'CIT-00475',
    citizenName: 'Arjun Mehta',
    citizenInitials: 'AM',
    service: 'Electricity Bill - New Connection',
    category: 'Utility',
    priority: 'low',
    status: 'submitted',
    assignedOperator: null,
    centre: 'Nalgonda Centre',
    submittedAt: '2026-08-02T17:35:00',
    slaHours: 72,
    slaRemainingHours: 60,
    amount: 200,
  },
  {
    id: 'APP-2026-8463',
    citizenId: 'CIT-00474',
    citizenName: 'Sunita Patel',
    citizenInitials: 'SP',
    service: 'PAN Card - Correction',
    category: 'PAN Card',
    priority: 'medium',
    status: 'under_review',
    assignedOperator: 'Sunita Rao',
    centre: 'Rangareddy Centre',
    submittedAt: '2026-08-02T12:45:00',
    slaHours: 48,
    slaRemainingHours: 20,
    amount: 110,
  },
  {
    id: 'APP-2026-8462',
    citizenId: 'CIT-00473',
    citizenName: 'Vikram Singh',
    citizenInitials: 'VS',
    service: 'Aadhaar Mobile Number Update',
    category: 'Aadhaar Services',
    priority: 'high',
    status: 'completed',
    assignedOperator: 'Amit Kumar',
    centre: 'Mahbubnagar Centre',
    submittedAt: '2026-08-02T09:00:00',
    slaHours: 24,
    slaRemainingHours: 0,
    amount: 50,
  },
];

export function findApplicationById(applicationId: string): ApplicationSummary | undefined {
  return APPLICATIONS.find((application) => application.id === applicationId);
}

const DEFAULT_DOCUMENTS: SupportingDocument[] = [
  { id: 'DOC-1', name: 'Aadhaar Card (Existing).pdf', type: 'Identity Proof', status: 'verified', uploadedAt: '2026-08-03T09:10:00' },
  { id: 'DOC-2', name: 'Electricity Bill.pdf', type: 'Address Proof', status: 'verified', uploadedAt: '2026-08-03T09:11:00' },
  { id: 'DOC-3', name: 'Passport Photo.jpg', type: 'Photograph', status: 'pending', uploadedAt: '2026-08-03T09:11:30' },
];

const DEFAULT_CHECKLIST: ChecklistItem[] = [
  { id: 'CHK-1', label: 'Identity proof verified', completed: true },
  { id: 'CHK-2', label: 'Address proof verified', completed: true },
  { id: 'CHK-3', label: 'Biometric match confirmed', completed: true },
  { id: 'CHK-4', label: 'Supervisor approval', completed: false },
  { id: 'CHK-5', label: 'Final quality check', completed: false },
];

const DEFAULT_PAYMENT: PaymentInformation = {
  status: 'paid',
  amount: 50,
  method: 'UPI',
  transactionId: 'TXN-90021847',
  paidAt: '2026-08-03T09:13:00',
};

const DEFAULT_TIMELINE: TimelineEvent[] = [
  {
    id: 'TL-1',
    title: 'Application Submitted',
    description: 'Citizen submitted Aadhaar address update request online.',
    timestamp: '2026-08-03T09:12:00',
    actor: 'Priya Sharma',
    completed: true,
  },
  {
    id: 'TL-2',
    title: 'Payment Received',
    description: 'Government fee of ₹50 collected via UPI.',
    timestamp: '2026-08-03T09:13:00',
    actor: 'System',
    completed: true,
  },
  {
    id: 'TL-3',
    title: 'Assigned for Review',
    description: 'Application assigned to Amit Kumar for verification.',
    timestamp: '2026-08-03T09:30:00',
    actor: 'System',
    completed: true,
  },
  {
    id: 'TL-4',
    title: 'Under Review',
    description: 'Operator reviewing submitted documents.',
    timestamp: '2026-08-03T10:05:00',
    actor: 'Amit Kumar',
    completed: true,
  },
  {
    id: 'TL-5',
    title: 'Approval Pending',
    description: 'Awaiting supervisor sign-off before processing.',
    timestamp: '',
    actor: '',
    completed: false,
  },
  {
    id: 'TL-6',
    title: 'Completed',
    description: 'Updated Aadhaar card dispatched to registered address.',
    timestamp: '',
    actor: '',
    completed: false,
  },
];

const DEFAULT_NOTES: InternalNote[] = [
  {
    id: 'NOTE-1',
    author: 'Amit Kumar',
    authorInitials: 'AK',
    content: 'Address proof matches existing records. Awaiting biometric re-verification before final approval.',
    createdAt: '2026-08-03T10:10:00',
  },
];

export function buildApplicationExtras(application: ApplicationSummary): Omit<ApplicationDetail, keyof ApplicationSummary> {
  return {
    documents: DEFAULT_DOCUMENTS,
    checklist: DEFAULT_CHECKLIST,
    payment: { ...DEFAULT_PAYMENT, amount: application.amount || DEFAULT_PAYMENT.amount },
    timeline: DEFAULT_TIMELINE,
    notes: DEFAULT_NOTES,
    formFieldKeys: [],
    formFields: [],
    documentRequirementOptions: DEFAULT_DOCUMENTS.filter((doc) => doc.documentRequirementId).map(
      (doc) => ({
        id: doc.documentRequirementId!,
        name: doc.name,
      }),
    ),
  };
}
